// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artifact struct {
	ID        int64              `json:"id"`
	RunID     int64              `json:"run_id"`
	Kind      string             `json:"kind"`
	Name      string             `json:"name"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Comment struct {
	ID          int64              `json:"id"`
	PublicID    pgtype.UUID        `json:"public_id"`
	OperationID int64              `json:"operation_id"`
	AuthorType  string             `json:"author_type"`
	AuthorID    pgtype.Int8        `json:"author_id"`
	Body        string             `json:"body"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Crew struct {
	ID        int64              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	FleetID   int64              `json:"fleet_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CrewMember struct {
	CrewID     int64  `json:"crew_id"`
	MemberType string `json:"member_type"`
	MemberID   int64  `json:"member_id"`
	Role       string `json:"role"`
}

type EnrollmentCode struct {
	ID        int64              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	FleetID   int64              `json:"fleet_id"`
	Code      string             `json:"code"`
	Label     string             `json:"label"`
	Reusable  bool               `json:"reusable"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Fleet struct {
	ID        int64              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	Name      string             `json:"name"`
	Kind      string             `json:"kind"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Invitation struct {
	ID           int64              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	FleetID      int64              `json:"fleet_id"`
	InviterID    int64              `json:"inviter_id"`
	InviteeEmail string             `json:"invitee_email"`
	Role         string             `json:"role"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

type Label struct {
	ID        int64              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	FleetID   int64              `json:"fleet_id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Membership struct {
	UserID    int64              `json:"user_id"`
	FleetID   int64              `json:"fleet_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Mission struct {
	ID        int64              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	FleetID   int64              `json:"fleet_id"`
	Name      string             `json:"name"`
	Key       string             `json:"key"`
	NextSeq   int32              `json:"next_seq"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Operation struct {
	ID               int64              `json:"id"`
	PublicID         pgtype.UUID        `json:"public_id"`
	FleetID          int64              `json:"fleet_id"`
	MissionID        int64              `json:"mission_id"`
	Seq              int32              `json:"seq"`
	ParentID         pgtype.Int8        `json:"parent_id"`
	Title            string             `json:"title"`
	Body             string             `json:"body"`
	Status           string             `json:"status"`
	Priority         int16              `json:"priority"`
	AssigneeType     pgtype.Text        `json:"assignee_type"`
	AssigneeID       pgtype.Int8        `json:"assignee_id"`
	RequiredTags     []string           `json:"required_tags"`
	ExcludedTags     []string           `json:"excluded_tags"`
	StartDate        pgtype.Date        `json:"start_date"`
	DueDate          pgtype.Date        `json:"due_date"`
	PilotSessionID   pgtype.Text        `json:"pilot_session_id"`
	PilotSessionKind pgtype.Text        `json:"pilot_session_kind"`
	SessionRoverID   pgtype.Int8        `json:"session_rover_id"`
	CreatedBy        pgtype.Int8        `json:"created_by"`
	Archived         bool               `json:"archived"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type OperationLabel struct {
	OperationID int64 `json:"operation_id"`
	LabelID     int64 `json:"label_id"`
}

type OperationRelation struct {
	ID        int64              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	FleetID   int64              `json:"fleet_id"`
	SourceID  int64              `json:"source_id"`
	TargetID  int64              `json:"target_id"`
	Kind      string             `json:"kind"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Pilot struct {
	ID        int64              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	FleetID   int64              `json:"fleet_id"`
	Name      string             `json:"name"`
	Kind      string             `json:"kind"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PullRequest struct {
	ID          int64              `json:"id"`
	PublicID    pgtype.UUID        `json:"public_id"`
	OperationID int64              `json:"operation_id"`
	Url         string             `json:"url"`
	Title       string             `json:"title"`
	State       string             `json:"state"`
	Number      pgtype.Int4        `json:"number"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Reaction struct {
	ID         int64              `json:"id"`
	TargetType string             `json:"target_type"`
	TargetID   int64              `json:"target_id"`
	UserID     int64              `json:"user_id"`
	Emoji      string             `json:"emoji"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Rover struct {
	ID               int64              `json:"id"`
	PublicID         pgtype.UUID        `json:"public_id"`
	FleetID          int64              `json:"fleet_id"`
	Name             string             `json:"name"`
	Token            string             `json:"token"`
	EnrollmentCodeID pgtype.Int8        `json:"enrollment_code_id"`
	Tags             []string           `json:"tags"`
	AutoTags         []string           `json:"auto_tags"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Run struct {
	ID              int64              `json:"id"`
	PublicID        pgtype.UUID        `json:"public_id"`
	FleetID         int64              `json:"fleet_id"`
	OperationID     int64              `json:"operation_id"`
	MissionID       pgtype.Int8        `json:"mission_id"`
	RoverID         pgtype.Int8        `json:"rover_id"`
	PilotID         pgtype.Int8        `json:"pilot_id"`
	RequiredRoverID pgtype.Int8        `json:"required_rover_id"`
	Pilot           string             `json:"pilot"`
	Command         string             `json:"command"`
	State           string             `json:"state"`
	SessionID       pgtype.Text        `json:"session_id"`
	NeedsInput      bool               `json:"needs_input"`
	RequestedStatus string             `json:"requested_status"`
	HeartbeatAt     pgtype.Timestamptz `json:"heartbeat_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type RunEvent struct {
	ID        int64              `json:"id"`
	RunID     int64              `json:"run_id"`
	Kind      string             `json:"kind"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RunMessage struct {
	ID        int64              `json:"id"`
	RunID     int64              `json:"run_id"`
	Seq       int32              `json:"seq"`
	Type      string             `json:"type"`
	Tool      pgtype.Text        `json:"tool"`
	Content   pgtype.Text        `json:"content"`
	Input     []byte             `json:"input"`
	Output    pgtype.Text        `json:"output"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	Token     string             `json:"token"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Signal struct {
	ID              int64              `json:"id"`
	PublicID        pgtype.UUID        `json:"public_id"`
	FleetID         int64              `json:"fleet_id"`
	RecipientUserID int64              `json:"recipient_user_id"`
	OperationID     pgtype.Int8        `json:"operation_id"`
	Type            string             `json:"type"`
	Severity        string             `json:"severity"`
	Title           string             `json:"title"`
	Body            string             `json:"body"`
	Read            bool               `json:"read"`
	Archived        bool               `json:"archived"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
