// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artifact struct {
	ID             int64              `json:"id"`
	PublicID       pgtype.UUID        `json:"public_id"`
	RunID          int64              `json:"run_id"`
	AssetID        pgtype.Int8        `json:"asset_id"`
	Kind           string             `json:"kind"`
	Name           string             `json:"name"`
	Content        string             `json:"content"`
	ContentPreview string             `json:"content_preview"`
	ByteSize       int64              `json:"byte_size"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Asset struct {
	ID             int64              `json:"id"`
	PublicID       pgtype.UUID        `json:"public_id"`
	FleetID        pgtype.Int8        `json:"fleet_id"`
	ObjectKey      string             `json:"object_key"`
	Filename       string             `json:"filename"`
	ContentType    string             `json:"content_type"`
	ByteSize       int64              `json:"byte_size"`
	Checksums      []byte             `json:"checksums"`
	StorageBackend string             `json:"storage_backend"`
	Status         string             `json:"status"`
	Metadata       []byte             `json:"metadata"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type Comment struct {
	ID              int64              `json:"id"`
	PublicID        pgtype.UUID        `json:"public_id"`
	OperationID     int64              `json:"operation_id"`
	AuthorType      string             `json:"author_type"`
	AuthorID        pgtype.Int8        `json:"author_id"`
	AuthorPilotKind pgtype.Text        `json:"author_pilot_kind"`
	Body            string             `json:"body"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Crew struct {
	ID        int64              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	FleetID   int64              `json:"fleet_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CrewMember struct {
	CrewID     int64              `json:"crew_id"`
	MemberType string             `json:"member_type"`
	UserID     pgtype.Int8        `json:"user_id"`
	PilotKind  pgtype.Text        `json:"pilot_kind"`
	Role       string             `json:"role"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type EnrollmentCode struct {
	ID            int64              `json:"id"`
	PublicID      pgtype.UUID        `json:"public_id"`
	FleetID       pgtype.Int8        `json:"fleet_id"`
	CodeHash      string             `json:"code_hash"`
	Kind          string             `json:"kind"`
	Name          string             `json:"name"`
	RemainingUses int32              `json:"remaining_uses"`
	Metadata      []byte             `json:"metadata"`
	CreatedBy     pgtype.Int8        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

type Fleet struct {
	ID        int64              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	Name      string             `json:"name"`
	Kind      string             `json:"kind"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Invitation struct {
	ID           int64              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	FleetID      int64              `json:"fleet_id"`
	InviterID    int64              `json:"inviter_id"`
	InviteeEmail string             `json:"invitee_email"`
	Role         string             `json:"role"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

type Label struct {
	ID        int64              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	FleetID   int64              `json:"fleet_id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Membership struct {
	UserID    int64              `json:"user_id"`
	FleetID   int64              `json:"fleet_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Mission struct {
	ID           int64              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	FleetID      int64              `json:"fleet_id"`
	Name         string             `json:"name"`
	Key          string             `json:"key"`
	NextSequence int32              `json:"next_sequence"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Operation struct {
	ID                  int64              `json:"id"`
	PublicID            pgtype.UUID        `json:"public_id"`
	FleetID             int64              `json:"fleet_id"`
	MissionID           int64              `json:"mission_id"`
	Sequence            int32              `json:"sequence"`
	MainOperationID     pgtype.Int8        `json:"main_operation_id"`
	Title               string             `json:"title"`
	Body                string             `json:"body"`
	Status              string             `json:"status"`
	Priority            int16              `json:"priority"`
	AssigneeType        pgtype.Text        `json:"assignee_type"`
	AssigneeID          pgtype.Int8        `json:"assignee_id"`
	AssigneePilotKind   pgtype.Text        `json:"assignee_pilot_kind"`
	RequiredTags        []string           `json:"required_tags"`
	ExcludedTags        []string           `json:"excluded_tags"`
	StartDate           pgtype.Date        `json:"start_date"`
	DueDate             pgtype.Date        `json:"due_date"`
	PilotSessionID      pgtype.Text        `json:"pilot_session_id"`
	PilotSessionKind    pgtype.Text        `json:"pilot_session_kind"`
	PilotSessionRoverID pgtype.Int8        `json:"pilot_session_rover_id"`
	Orchestrating       bool               `json:"orchestrating"`
	Archived            bool               `json:"archived"`
	Metadata            []byte             `json:"metadata"`
	CreatedBy           pgtype.Int8        `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	FinishedAt          pgtype.Timestamptz `json:"finished_at"`
}

type OperationLabel struct {
	OperationID int64 `json:"operation_id"`
	LabelID     int64 `json:"label_id"`
}

type OperationRelation struct {
	ID        int64              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	FleetID   int64              `json:"fleet_id"`
	SourceID  int64              `json:"source_id"`
	TargetID  int64              `json:"target_id"`
	Kind      string             `json:"kind"`
	CreatedBy pgtype.Int8        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PullRequest struct {
	ID          int64              `json:"id"`
	PublicID    pgtype.UUID        `json:"public_id"`
	OperationID int64              `json:"operation_id"`
	Url         string             `json:"url"`
	Title       string             `json:"title"`
	Status      string             `json:"status"`
	Number      pgtype.Int4        `json:"number"`
	Metadata    []byte             `json:"metadata"`
	CreatedBy   pgtype.Int8        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Pulse struct {
	ID          int64              `json:"id"`
	PublicID    pgtype.UUID        `json:"public_id"`
	FleetID     int64              `json:"fleet_id"`
	RoutineID   int64              `json:"routine_id"`
	OperationID pgtype.Int8        `json:"operation_id"`
	Status      string             `json:"status"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
}

type Reaction struct {
	ID         int64              `json:"id"`
	TargetType string             `json:"target_type"`
	TargetID   int64              `json:"target_id"`
	UserID     int64              `json:"user_id"`
	Emoji      string             `json:"emoji"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Routine struct {
	ID                int64              `json:"id"`
	PublicID          pgtype.UUID        `json:"public_id"`
	FleetID           int64              `json:"fleet_id"`
	MissionID         int64              `json:"mission_id"`
	Title             string             `json:"title"`
	Body              string             `json:"body"`
	Metadata          []byte             `json:"metadata"`
	OperationMetadata []byte             `json:"operation_metadata"`
	CreatedBy         pgtype.Int8        `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	NextPulseAt       pgtype.Timestamptz `json:"next_pulse_at"`
	LastPulsedAt      pgtype.Timestamptz `json:"last_pulsed_at"`
}

type Rover struct {
	ID               int64              `json:"id"`
	PublicID         pgtype.UUID        `json:"public_id"`
	FleetID          int64              `json:"fleet_id"`
	Name             string             `json:"name"`
	EnrollmentCodeID pgtype.Int8        `json:"enrollment_code_id"`
	TokenHash        string             `json:"token_hash"`
	Units            int32              `json:"units"`
	AutoTags         []string           `json:"auto_tags"`
	Tags             []string           `json:"tags"`
	Metadata         []byte             `json:"metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
}

type Run struct {
	ID              int64              `json:"id"`
	PublicID        pgtype.UUID        `json:"public_id"`
	FleetID         int64              `json:"fleet_id"`
	OperationID     int64              `json:"operation_id"`
	MissionID       pgtype.Int8        `json:"mission_id"`
	RoverID         pgtype.Int8        `json:"rover_id"`
	RequiredRoverID pgtype.Int8        `json:"required_rover_id"`
	Pilot           string             `json:"pilot"`
	Command         string             `json:"command"`
	Status          string             `json:"status"`
	SessionID       pgtype.Text        `json:"session_id"`
	NeedsInput      bool               `json:"needs_input"`
	RequestedStatus string             `json:"requested_status"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	HeartbeatAt     pgtype.Timestamptz `json:"heartbeat_at"`
	FinalizedAt     pgtype.Timestamptz `json:"finalized_at"`
}

type RunEvent struct {
	ID        int64              `json:"id"`
	RunID     int64              `json:"run_id"`
	Kind      string             `json:"kind"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RunMessage struct {
	ID        int64              `json:"id"`
	RunID     int64              `json:"run_id"`
	Sequence  int32              `json:"sequence"`
	Type      string             `json:"type"`
	Tool      pgtype.Text        `json:"tool"`
	Content   pgtype.Text        `json:"content"`
	Input     []byte             `json:"input"`
	Output    pgtype.Text        `json:"output"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	TokenHash string             `json:"token_hash"`
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Signal struct {
	ID              int64              `json:"id"`
	PublicID        pgtype.UUID        `json:"public_id"`
	FleetID         int64              `json:"fleet_id"`
	RecipientUserID int64              `json:"recipient_user_id"`
	OperationID     pgtype.Int8        `json:"operation_id"`
	Type            string             `json:"type"`
	Severity        string             `json:"severity"`
	Title           string             `json:"title"`
	Body            string             `json:"body"`
	Read            bool               `json:"read"`
	Archived        bool               `json:"archived"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type SourceAction struct {
	ID            int64              `json:"id"`
	PublicID      pgtype.UUID        `json:"public_id"`
	FleetID       int64              `json:"fleet_id"`
	OperationID   int64              `json:"operation_id"`
	RunID         pgtype.Int8        `json:"run_id"`
	RoverID       pgtype.Int8        `json:"rover_id"`
	Kind          string             `json:"kind"`
	Status        string             `json:"status"`
	BranchName    string             `json:"branch_name"`
	CommitSha     string             `json:"commit_sha"`
	BaseSha       string             `json:"base_sha"`
	SourceHeadSha string             `json:"source_head_sha"`
	Message       string             `json:"message"`
	Metadata      []byte             `json:"metadata"`
	CreatedBy     pgtype.Int8        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	AcceptedAt    pgtype.Timestamptz `json:"accepted_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

type User struct {
	ID           int64              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
