// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCrewMember = `-- name: AddCrewMember :exec
insert into crew_members (crew_id, member_type, member_id, role)
values ($1, $2, $3, $4)
on conflict (crew_id, member_type, member_id) do update set role = excluded.role
`

type AddCrewMemberParams struct {
	CrewID     int64  `json:"crew_id"`
	MemberType string `json:"member_type"`
	MemberID   int64  `json:"member_id"`
	Role       string `json:"role"`
}

func (q *Queries) AddCrewMember(ctx context.Context, arg AddCrewMemberParams) error {
	_, err := q.db.Exec(ctx, addCrewMember,
		arg.CrewID,
		arg.MemberType,
		arg.MemberID,
		arg.Role,
	)
	return err
}

const addOperationLabel = `-- name: AddOperationLabel :exec
insert into operation_labels (operation_id, label_id) values ($1, $2) on conflict do nothing
`

type AddOperationLabelParams struct {
	OperationID int64 `json:"operation_id"`
	LabelID     int64 `json:"label_id"`
}

func (q *Queries) AddOperationLabel(ctx context.Context, arg AddOperationLabelParams) error {
	_, err := q.db.Exec(ctx, addOperationLabel, arg.OperationID, arg.LabelID)
	return err
}

const addReaction = `-- name: AddReaction :exec
insert into reactions (target_type, target_id, user_id, emoji) values ($1, $2, $3, $4) on conflict do nothing
`

type AddReactionParams struct {
	TargetType string `json:"target_type"`
	TargetID   int64  `json:"target_id"`
	UserID     int64  `json:"user_id"`
	Emoji      string `json:"emoji"`
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) error {
	_, err := q.db.Exec(ctx, addReaction,
		arg.TargetType,
		arg.TargetID,
		arg.UserID,
		arg.Emoji,
	)
	return err
}

const appendArtifact = `-- name: AppendArtifact :one
insert into artifacts (run_id, kind, name, content)
values ($1, $2, $3, $4)
returning id, run_id, kind, name, content, created_at
`

type AppendArtifactParams struct {
	RunID   int64  `json:"run_id"`
	Kind    string `json:"kind"`
	Name    string `json:"name"`
	Content string `json:"content"`
}

func (q *Queries) AppendArtifact(ctx context.Context, arg AppendArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, appendArtifact,
		arg.RunID,
		arg.Kind,
		arg.Name,
		arg.Content,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const appendRunEvent = `-- name: AppendRunEvent :one

insert into run_events (run_id, kind, message)
values ($1, $2, $3)
returning id, run_id, kind, message, created_at
`

type AppendRunEventParams struct {
	RunID   int64  `json:"run_id"`
	Kind    string `json:"kind"`
	Message string `json:"message"`
}

// ===================== events & artifacts ====================
func (q *Queries) AppendRunEvent(ctx context.Context, arg AppendRunEventParams) (RunEvent, error) {
	row := q.db.QueryRow(ctx, appendRunEvent, arg.RunID, arg.Kind, arg.Message)
	var i RunEvent
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const appendRunMessage = `-- name: AppendRunMessage :one

insert into run_messages (run_id, seq, type, tool, content, input, output)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, run_id, seq, type, tool, content, input, output, created_at
`

type AppendRunMessageParams struct {
	RunID   int64       `json:"run_id"`
	Seq     int32       `json:"seq"`
	Type    string      `json:"type"`
	Tool    pgtype.Text `json:"tool"`
	Content pgtype.Text `json:"content"`
	Input   []byte      `json:"input"`
	Output  pgtype.Text `json:"output"`
}

// ===================== transcript (run messages) =============
func (q *Queries) AppendRunMessage(ctx context.Context, arg AppendRunMessageParams) (RunMessage, error) {
	row := q.db.QueryRow(ctx, appendRunMessage,
		arg.RunID,
		arg.Seq,
		arg.Type,
		arg.Tool,
		arg.Content,
		arg.Input,
		arg.Output,
	)
	var i RunMessage
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Seq,
		&i.Type,
		&i.Tool,
		&i.Content,
		&i.Input,
		&i.Output,
		&i.CreatedAt,
	)
	return i, err
}

const archiveActionRequiredForOperation = `-- name: ArchiveActionRequiredForOperation :exec
update signals set archived = true
where operation_id = $1 and severity = 'action_required' and archived = false
`

// Self-heal: archive open action-required signals once an op leaves that state.
func (q *Queries) ArchiveActionRequiredForOperation(ctx context.Context, operationID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, archiveActionRequiredForOperation, operationID)
	return err
}

const archiveSignal = `-- name: ArchiveSignal :exec
update signals set archived = true, read = true
where id = $1 and fleet_id = $2 and recipient_user_id = $3
`

type ArchiveSignalParams struct {
	ID              int64 `json:"id"`
	FleetID         int64 `json:"fleet_id"`
	RecipientUserID int64 `json:"recipient_user_id"`
}

func (q *Queries) ArchiveSignal(ctx context.Context, arg ArchiveSignalParams) error {
	_, err := q.db.Exec(ctx, archiveSignal, arg.ID, arg.FleetID, arg.RecipientUserID)
	return err
}

const assignOperation = `-- name: AssignOperation :one
update operations set assignee_type = $3, assignee_id = $4, updated_at = now()
where id = $1 and fleet_id = $2
returning id, public_id, fleet_id, mission_id, seq, parent_id, title, body, status, priority, assignee_type, assignee_id, required_tags, excluded_tags, start_date, due_date, pilot_session_id, pilot_session_kind, session_rover_id, created_by, archived, created_at, updated_at
`

type AssignOperationParams struct {
	ID           int64       `json:"id"`
	FleetID      int64       `json:"fleet_id"`
	AssigneeType pgtype.Text `json:"assignee_type"`
	AssigneeID   pgtype.Int8 `json:"assignee_id"`
}

func (q *Queries) AssignOperation(ctx context.Context, arg AssignOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, assignOperation,
		arg.ID,
		arg.FleetID,
		arg.AssigneeType,
		arg.AssigneeID,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.MissionID,
		&i.Seq,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Priority,
		&i.AssigneeType,
		&i.AssigneeID,
		&i.RequiredTags,
		&i.ExcludedTags,
		&i.StartDate,
		&i.DueDate,
		&i.PilotSessionID,
		&i.PilotSessionKind,
		&i.SessionRoverID,
		&i.CreatedBy,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const bumpMissionSeq = `-- name: BumpMissionSeq :one
update missions set next_seq = next_seq + 1
where id = $1 and fleet_id = $2
returning next_seq
`

type BumpMissionSeqParams struct {
	ID      int64 `json:"id"`
	FleetID int64 `json:"fleet_id"`
}

// Atomically allocate the next per-mission operation number.
func (q *Queries) BumpMissionSeq(ctx context.Context, arg BumpMissionSeqParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpMissionSeq, arg.ID, arg.FleetID)
	var next_seq int32
	err := row.Scan(&next_seq)
	return next_seq, err
}

const claimNextRun = `-- name: ClaimNextRun :one
update runs
set state = 'claimed', updated_at = now(), heartbeat_at = now(), rover_id = $2
where id = (
    select r.id from runs r
    join operations o on o.id = r.operation_id
    where r.state = 'queued' and r.fleet_id = $1
      and (r.required_rover_id is null or r.required_rover_id = $2) -- session affinity pin
      and ('pilot:' || r.pilot) = any($3::text[]) -- pilot capability tag
      and not (o.excluded_tags && $3::text[])      -- deny boundary
      and o.required_tags <@ $3::text[]            -- allow list
    order by r.id
    for update of r skip locked
    limit 1
)
returning id, public_id, fleet_id, operation_id, mission_id, rover_id, pilot_id, required_rover_id, pilot, command, state, session_id, needs_input, requested_status, heartbeat_at, created_at, updated_at
`

type ClaimNextRunParams struct {
	FleetID int64       `json:"fleet_id"`
	RoverID pgtype.Int8 `json:"rover_id"`
	Column3 []string    `json:"column_3"`
}

// Atomically grab the oldest queued run in a fleet and attribute it to the
// claiming rover.
// Claim the oldest queued run the rover is allowed and able to run: the rover
// must advertise the run's pilot kind, the operation deny list must not overlap
// its tags (checked first), and its allow list must be a subset.
// $3 = the rover's tag union (tags || auto_tags).
func (q *Queries) ClaimNextRun(ctx context.Context, arg ClaimNextRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, claimNextRun, arg.FleetID, arg.RoverID, arg.Column3)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.OperationID,
		&i.MissionID,
		&i.RoverID,
		&i.PilotID,
		&i.RequiredRoverID,
		&i.Pilot,
		&i.Command,
		&i.State,
		&i.SessionID,
		&i.NeedsInput,
		&i.RequestedStatus,
		&i.HeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countActiveRuns = `-- name: CountActiveRuns :one
select count(distinct operation_id)::bigint from runs
where fleet_id = $1 and state in ('queued', 'claimed', 'starting', 'running')
`

// Operations in the fleet with an in-flight run (for the board's "N working" pill).
func (q *Queries) CountActiveRuns(ctx context.Context, fleetID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRuns, fleetID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countFleetOwners = `-- name: CountFleetOwners :one
select count(*) from memberships where fleet_id = $1 and role = 'owner'
`

func (q *Queries) CountFleetOwners(ctx context.Context, fleetID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFleetOwners, fleetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOperationsByMission = `-- name: CountOperationsByMission :many
select m.public_id as mission_id, count(*)::bigint as n
from operations o join missions m on m.id = o.mission_id
where o.fleet_id = $1
group by m.public_id
`

type CountOperationsByMissionRow struct {
	MissionID pgtype.UUID `json:"mission_id"`
	N         int64       `json:"n"`
}

// Per-mission operation counts (for the Missions view), keyed by mission public id.
func (q *Queries) CountOperationsByMission(ctx context.Context, fleetID int64) ([]CountOperationsByMissionRow, error) {
	rows, err := q.db.Query(ctx, countOperationsByMission, fleetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOperationsByMissionRow{}
	for rows.Next() {
		var i CountOperationsByMissionRow
		if err := rows.Scan(&i.MissionID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOperationsByStatus = `-- name: CountOperationsByStatus :many
select status, count(*)::bigint as n from operations
where fleet_id = $1 and ($2::bigint = 0 or mission_id = $2)
  and ($3::smallint = -1 or priority = $3)
  and ($4::text = '' or assignee_type = $4)
  and ($5::bigint = 0 or assignee_id = $5)
  and ($6::bigint = 0 or created_by = $6)
  and ($7::bigint = 0 or exists(select 1 from operation_labels ol where ol.operation_id = operations.id and ol.label_id = $7))
  and ($8::bool or archived = false)
group by status
`

type CountOperationsByStatusParams struct {
	FleetID int64  `json:"fleet_id"`
	Column2 int64  `json:"column_2"`
	Column3 int16  `json:"column_3"`
	Column4 string `json:"column_4"`
	Column5 int64  `json:"column_5"`
	Column6 int64  `json:"column_6"`
	Column7 int64  `json:"column_7"`
	Column8 bool   `json:"column_8"`
}

type CountOperationsByStatusRow struct {
	Status string `json:"status"`
	N      int64  `json:"n"`
}

// Board column counts (optionally scoped to one mission). mission = 0 → all.
func (q *Queries) CountOperationsByStatus(ctx context.Context, arg CountOperationsByStatusParams) ([]CountOperationsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countOperationsByStatus,
		arg.FleetID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOperationsByStatusRow{}
	for rows.Next() {
		var i CountOperationsByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createComment = `-- name: CreateComment :one

insert into comments (operation_id, author_type, author_id, body)
values ($1, $2, $3, $4)
returning id, public_id, operation_id, author_type, author_id, body, created_at
`

type CreateCommentParams struct {
	OperationID int64       `json:"operation_id"`
	AuthorType  string      `json:"author_type"`
	AuthorID    pgtype.Int8 `json:"author_id"`
	Body        string      `json:"body"`
}

// ========================= comments ==========================
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.OperationID,
		arg.AuthorType,
		arg.AuthorID,
		arg.Body,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OperationID,
		&i.AuthorType,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const createCrew = `-- name: CreateCrew :one

insert into crews (fleet_id, name) values ($1, $2) returning id, public_id, fleet_id, name, created_at
`

type CreateCrewParams struct {
	FleetID int64  `json:"fleet_id"`
	Name    string `json:"name"`
}

// ========================== crews ============================
func (q *Queries) CreateCrew(ctx context.Context, arg CreateCrewParams) (Crew, error) {
	row := q.db.QueryRow(ctx, createCrew, arg.FleetID, arg.Name)
	var i Crew
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createEnrollmentCode = `-- name: CreateEnrollmentCode :one

insert into enrollment_codes (fleet_id, code, label, reusable, expires_at)
values ($1, $2, $3, $4, $5)
returning id, public_id, fleet_id, code, label, reusable, expires_at, created_at
`

type CreateEnrollmentCodeParams struct {
	FleetID   int64              `json:"fleet_id"`
	Code      string             `json:"code"`
	Label     string             `json:"label"`
	Reusable  bool               `json:"reusable"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// ---- enrollment codes (enrollment) ----
func (q *Queries) CreateEnrollmentCode(ctx context.Context, arg CreateEnrollmentCodeParams) (EnrollmentCode, error) {
	row := q.db.QueryRow(ctx, createEnrollmentCode,
		arg.FleetID,
		arg.Code,
		arg.Label,
		arg.Reusable,
		arg.ExpiresAt,
	)
	var i EnrollmentCode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.Code,
		&i.Label,
		&i.Reusable,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createFleet = `-- name: CreateFleet :one

insert into fleets (name, kind)
values ($1, $2)
returning id, public_id, name, kind, created_at
`

type CreateFleetParams struct {
	Name string `json:"name"`
	Kind string `json:"kind"`
}

// ========================== tenancy ==========================
func (q *Queries) CreateFleet(ctx context.Context, arg CreateFleetParams) (Fleet, error) {
	row := q.db.QueryRow(ctx, createFleet, arg.Name, arg.Kind)
	var i Fleet
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one

insert into invitations (fleet_id, inviter_id, invitee_email, role)
values ($1, $2, $3, $4)
returning id, public_id, fleet_id, inviter_id, invitee_email, role, status, created_at, expires_at
`

type CreateInvitationParams struct {
	FleetID      int64  `json:"fleet_id"`
	InviterID    int64  `json:"inviter_id"`
	InviteeEmail string `json:"invitee_email"`
	Role         string `json:"role"`
}

// ===================== invitations ===========================
func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.FleetID,
		arg.InviterID,
		arg.InviteeEmail,
		arg.Role,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.InviterID,
		&i.InviteeEmail,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createLabel = `-- name: CreateLabel :one

insert into labels (fleet_id, name, color) values ($1, $2, $3) returning id, public_id, fleet_id, name, color, created_at
`

type CreateLabelParams struct {
	FleetID int64  `json:"fleet_id"`
	Name    string `json:"name"`
	Color   string `json:"color"`
}

// ============================ labels =============================
func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, createLabel, arg.FleetID, arg.Name, arg.Color)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const createMembership = `-- name: CreateMembership :exec
insert into memberships (user_id, fleet_id, role)
values ($1, $2, $3)
on conflict (user_id, fleet_id) do nothing
`

type CreateMembershipParams struct {
	UserID  int64  `json:"user_id"`
	FleetID int64  `json:"fleet_id"`
	Role    string `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.UserID, arg.FleetID, arg.Role)
	return err
}

const createMission = `-- name: CreateMission :one

insert into missions (fleet_id, name, key)
values ($1, $2, $3)
returning id, public_id, fleet_id, name, key, next_seq, created_at
`

type CreateMissionParams struct {
	FleetID int64  `json:"fleet_id"`
	Name    string `json:"name"`
	Key     string `json:"key"`
}

// ========================= missions ==========================
// A mission is a user-created objective: a grouping of operations within a
// fleet. Its key prefixes operation codes; runs execute in per-operation
// isolated dirs managed by the rover.
func (q *Queries) CreateMission(ctx context.Context, arg CreateMissionParams) (Mission, error) {
	row := q.db.QueryRow(ctx, createMission, arg.FleetID, arg.Name, arg.Key)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.Name,
		&i.Key,
		&i.NextSeq,
		&i.CreatedAt,
	)
	return i, err
}

const createOperation = `-- name: CreateOperation :one

insert into operations (fleet_id, title, body, mission_id, assignee_type, assignee_id, status, seq, required_tags, excluded_tags, priority, parent_id, start_date, due_date, created_by)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
returning id, public_id, fleet_id, mission_id, seq, parent_id, title, body, status, priority, assignee_type, assignee_id, required_tags, excluded_tags, start_date, due_date, pilot_session_id, pilot_session_kind, session_rover_id, created_by, archived, created_at, updated_at
`

type CreateOperationParams struct {
	FleetID      int64       `json:"fleet_id"`
	Title        string      `json:"title"`
	Body         string      `json:"body"`
	MissionID    int64       `json:"mission_id"`
	AssigneeType pgtype.Text `json:"assignee_type"`
	AssigneeID   pgtype.Int8 `json:"assignee_id"`
	Status       string      `json:"status"`
	Seq          int32       `json:"seq"`
	RequiredTags []string    `json:"required_tags"`
	ExcludedTags []string    `json:"excluded_tags"`
	Priority     int16       `json:"priority"`
	ParentID     pgtype.Int8 `json:"parent_id"`
	StartDate    pgtype.Date `json:"start_date"`
	DueDate      pgtype.Date `json:"due_date"`
	CreatedBy    pgtype.Int8 `json:"created_by"`
}

// ========================== operations ===========================
func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, createOperation,
		arg.FleetID,
		arg.Title,
		arg.Body,
		arg.MissionID,
		arg.AssigneeType,
		arg.AssigneeID,
		arg.Status,
		arg.Seq,
		arg.RequiredTags,
		arg.ExcludedTags,
		arg.Priority,
		arg.ParentID,
		arg.StartDate,
		arg.DueDate,
		arg.CreatedBy,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.MissionID,
		&i.Seq,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Priority,
		&i.AssigneeType,
		&i.AssigneeID,
		&i.RequiredTags,
		&i.ExcludedTags,
		&i.StartDate,
		&i.DueDate,
		&i.PilotSessionID,
		&i.PilotSessionKind,
		&i.SessionRoverID,
		&i.CreatedBy,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPR = `-- name: CreatePR :one

insert into pull_requests (operation_id, url, title, number) values ($1, $2, $3, $4) returning id, public_id, operation_id, url, title, state, number, created_at
`

type CreatePRParams struct {
	OperationID int64       `json:"operation_id"`
	Url         string      `json:"url"`
	Title       string      `json:"title"`
	Number      pgtype.Int4 `json:"number"`
}

// ========================= pull requests =========================
func (q *Queries) CreatePR(ctx context.Context, arg CreatePRParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, createPR,
		arg.OperationID,
		arg.Url,
		arg.Title,
		arg.Number,
	)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OperationID,
		&i.Url,
		&i.Title,
		&i.State,
		&i.Number,
		&i.CreatedAt,
	)
	return i, err
}

const createPilot = `-- name: CreatePilot :one

insert into pilots (fleet_id, name, kind) values ($1, $2, $3) returning id, public_id, fleet_id, name, kind, created_at
`

type CreatePilotParams struct {
	FleetID int64  `json:"fleet_id"`
	Name    string `json:"name"`
	Kind    string `json:"kind"`
}

// ========================= pilots ============================
func (q *Queries) CreatePilot(ctx context.Context, arg CreatePilotParams) (Pilot, error) {
	row := q.db.QueryRow(ctx, createPilot, arg.FleetID, arg.Name, arg.Kind)
	var i Pilot
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const createRelation = `-- name: CreateRelation :one

insert into operation_relations (fleet_id, source_id, target_id, kind)
values ($1, $2, $3, $4)
on conflict (source_id, target_id, kind) do update set kind = excluded.kind
returning id, public_id, fleet_id, source_id, target_id, kind, created_at
`

type CreateRelationParams struct {
	FleetID  int64  `json:"fleet_id"`
	SourceID int64  `json:"source_id"`
	TargetID int64  `json:"target_id"`
	Kind     string `json:"kind"`
}

// ====================== operation relations ========================
func (q *Queries) CreateRelation(ctx context.Context, arg CreateRelationParams) (OperationRelation, error) {
	row := q.db.QueryRow(ctx, createRelation,
		arg.FleetID,
		arg.SourceID,
		arg.TargetID,
		arg.Kind,
	)
	var i OperationRelation
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.SourceID,
		&i.TargetID,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const createRover = `-- name: CreateRover :one

insert into rovers (fleet_id, name, token, enrollment_code_id, tags, auto_tags)
values ($1, $2, $3, $4, $5, $6)
returning id, public_id, fleet_id, name, token, enrollment_code_id, tags, auto_tags, last_seen_at, created_at
`

type CreateRoverParams struct {
	FleetID          int64       `json:"fleet_id"`
	Name             string      `json:"name"`
	Token            string      `json:"token"`
	EnrollmentCodeID pgtype.Int8 `json:"enrollment_code_id"`
	Tags             []string    `json:"tags"`
	AutoTags         []string    `json:"auto_tags"`
}

// ---- rovers (per-rover identity + connection token) ----
func (q *Queries) CreateRover(ctx context.Context, arg CreateRoverParams) (Rover, error) {
	row := q.db.QueryRow(ctx, createRover,
		arg.FleetID,
		arg.Name,
		arg.Token,
		arg.EnrollmentCodeID,
		arg.Tags,
		arg.AutoTags,
	)
	var i Rover
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.Name,
		&i.Token,
		&i.EnrollmentCodeID,
		&i.Tags,
		&i.AutoTags,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one

insert into runs (fleet_id, operation_id, mission_id, command, pilot, pilot_id, session_id, required_rover_id)
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, public_id, fleet_id, operation_id, mission_id, rover_id, pilot_id, required_rover_id, pilot, command, state, session_id, needs_input, requested_status, heartbeat_at, created_at, updated_at
`

type CreateRunParams struct {
	FleetID         int64       `json:"fleet_id"`
	OperationID     int64       `json:"operation_id"`
	MissionID       pgtype.Int8 `json:"mission_id"`
	Command         string      `json:"command"`
	Pilot           string      `json:"pilot"`
	PilotID         pgtype.Int8 `json:"pilot_id"`
	SessionID       pgtype.Text `json:"session_id"`
	RequiredRoverID pgtype.Int8 `json:"required_rover_id"`
}

// =========================== runs ============================
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.FleetID,
		arg.OperationID,
		arg.MissionID,
		arg.Command,
		arg.Pilot,
		arg.PilotID,
		arg.SessionID,
		arg.RequiredRoverID,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.OperationID,
		&i.MissionID,
		&i.RoverID,
		&i.PilotID,
		&i.RequiredRoverID,
		&i.Pilot,
		&i.Command,
		&i.State,
		&i.SessionID,
		&i.NeedsInput,
		&i.RequestedStatus,
		&i.HeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
insert into sessions (token, user_id, expires_at)
values ($1, $2, $3)
`

type CreateSessionParams struct {
	Token     string             `json:"token"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const createSignal = `-- name: CreateSignal :one

insert into signals (fleet_id, recipient_user_id, operation_id, type, severity, title, body)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, public_id, fleet_id, recipient_user_id, operation_id, type, severity, title, body, read, archived, created_at
`

type CreateSignalParams struct {
	FleetID         int64       `json:"fleet_id"`
	RecipientUserID int64       `json:"recipient_user_id"`
	OperationID     pgtype.Int8 `json:"operation_id"`
	Type            string      `json:"type"`
	Severity        string      `json:"severity"`
	Title           string      `json:"title"`
	Body            string      `json:"body"`
}

// ========================== signals ==========================
func (q *Queries) CreateSignal(ctx context.Context, arg CreateSignalParams) (Signal, error) {
	row := q.db.QueryRow(ctx, createSignal,
		arg.FleetID,
		arg.RecipientUserID,
		arg.OperationID,
		arg.Type,
		arg.Severity,
		arg.Title,
		arg.Body,
	)
	var i Signal
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.RecipientUserID,
		&i.OperationID,
		&i.Type,
		&i.Severity,
		&i.Title,
		&i.Body,
		&i.Read,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

insert into users (email, password_hash, name)
values ($1, $2, $3)
returning id, public_id, email, password_hash, name, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
}

// ============================ auth ============================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCrew = `-- name: DeleteCrew :exec
delete from crews where id = $1 and fleet_id = $2
`

type DeleteCrewParams struct {
	ID      int64 `json:"id"`
	FleetID int64 `json:"fleet_id"`
}

func (q *Queries) DeleteCrew(ctx context.Context, arg DeleteCrewParams) error {
	_, err := q.db.Exec(ctx, deleteCrew, arg.ID, arg.FleetID)
	return err
}

const deleteEnrollmentCode = `-- name: DeleteEnrollmentCode :exec
delete from enrollment_codes where id = $1 and fleet_id = $2
`

type DeleteEnrollmentCodeParams struct {
	ID      int64 `json:"id"`
	FleetID int64 `json:"fleet_id"`
}

func (q *Queries) DeleteEnrollmentCode(ctx context.Context, arg DeleteEnrollmentCodeParams) error {
	_, err := q.db.Exec(ctx, deleteEnrollmentCode, arg.ID, arg.FleetID)
	return err
}

const deleteFleet = `-- name: DeleteFleet :exec
delete from fleets where id = $1
`

func (q *Queries) DeleteFleet(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFleet, id)
	return err
}

const deleteLabel = `-- name: DeleteLabel :exec
delete from labels where id = $1 and fleet_id = $2
`

type DeleteLabelParams struct {
	ID      int64 `json:"id"`
	FleetID int64 `json:"fleet_id"`
}

func (q *Queries) DeleteLabel(ctx context.Context, arg DeleteLabelParams) error {
	_, err := q.db.Exec(ctx, deleteLabel, arg.ID, arg.FleetID)
	return err
}

const deletePR = `-- name: DeletePR :exec
delete from pull_requests p using operations o
where p.public_id = $1 and p.operation_id = o.id and o.fleet_id = $2
`

type DeletePRParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	FleetID  int64       `json:"fleet_id"`
}

func (q *Queries) DeletePR(ctx context.Context, arg DeletePRParams) error {
	_, err := q.db.Exec(ctx, deletePR, arg.PublicID, arg.FleetID)
	return err
}

const deletePilot = `-- name: DeletePilot :exec
delete from pilots where id = $1 and fleet_id = $2
`

type DeletePilotParams struct {
	ID      int64 `json:"id"`
	FleetID int64 `json:"fleet_id"`
}

func (q *Queries) DeletePilot(ctx context.Context, arg DeletePilotParams) error {
	_, err := q.db.Exec(ctx, deletePilot, arg.ID, arg.FleetID)
	return err
}

const deleteRelation = `-- name: DeleteRelation :exec
delete from operation_relations where public_id = $1 and fleet_id = $2
`

type DeleteRelationParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	FleetID  int64       `json:"fleet_id"`
}

func (q *Queries) DeleteRelation(ctx context.Context, arg DeleteRelationParams) error {
	_, err := q.db.Exec(ctx, deleteRelation, arg.PublicID, arg.FleetID)
	return err
}

const deleteRover = `-- name: DeleteRover :exec
delete from rovers where id = $1 and fleet_id = $2
`

type DeleteRoverParams struct {
	ID      int64 `json:"id"`
	FleetID int64 `json:"fleet_id"`
}

func (q *Queries) DeleteRover(ctx context.Context, arg DeleteRoverParams) error {
	_, err := q.db.Exec(ctx, deleteRover, arg.ID, arg.FleetID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
delete from sessions where token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const fleetsWithNewlyOfflineRovers = `-- name: FleetsWithNewlyOfflineRovers :many
select distinct fleet_id from rovers
where last_seen_at is not null
  and last_seen_at <  now() - make_interval(secs => $1::float8)
  and last_seen_at >= now() - make_interval(secs => $2::float8)
`

type FleetsWithNewlyOfflineRoversParams struct {
	Column1 float64 `json:"column_1"`
	Column2 float64 `json:"column_2"`
}

// Fleets whose rovers just crossed the offline threshold (so the sweeper can push
// a presence update — absence of heartbeat isn't itself an event).
func (q *Queries) FleetsWithNewlyOfflineRovers(ctx context.Context, arg FleetsWithNewlyOfflineRoversParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, fleetsWithNewlyOfflineRovers, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var fleet_id int64
		if err := rows.Scan(&fleet_id); err != nil {
			return nil, err
		}
		items = append(items, fleet_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentIDByPublicID = `-- name: GetCommentIDByPublicID :one

select c.id from comments c join operations o on o.id = c.operation_id
where c.public_id = $1 and o.fleet_id = $2
`

type GetCommentIDByPublicIDParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	FleetID  int64       `json:"fleet_id"`
}

// ====================== reactions ========================
func (q *Queries) GetCommentIDByPublicID(ctx context.Context, arg GetCommentIDByPublicIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getCommentIDByPublicID, arg.PublicID, arg.FleetID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCrew = `-- name: GetCrew :one
select id, public_id, fleet_id, name, created_at from crews where id = $1 and fleet_id = $2
`

type GetCrewParams struct {
	ID      int64 `json:"id"`
	FleetID int64 `json:"fleet_id"`
}

func (q *Queries) GetCrew(ctx context.Context, arg GetCrewParams) (Crew, error) {
	row := q.db.QueryRow(ctx, getCrew, arg.ID, arg.FleetID)
	var i Crew
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getCrewIDByPublicID = `-- name: GetCrewIDByPublicID :one
select id from crews where public_id = $1 and fleet_id = $2
`

type GetCrewIDByPublicIDParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	FleetID  int64       `json:"fleet_id"`
}

func (q *Queries) GetCrewIDByPublicID(ctx context.Context, arg GetCrewIDByPublicIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getCrewIDByPublicID, arg.PublicID, arg.FleetID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getEnrollmentCodeForUpdate = `-- name: GetEnrollmentCodeForUpdate :one
select id, public_id, fleet_id, code, label, reusable, expires_at, created_at from enrollment_codes where code = $1 for update
`

func (q *Queries) GetEnrollmentCodeForUpdate(ctx context.Context, code string) (EnrollmentCode, error) {
	row := q.db.QueryRow(ctx, getEnrollmentCodeForUpdate, code)
	var i EnrollmentCode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.Code,
		&i.Label,
		&i.Reusable,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEnrollmentCodeIDByPublicID = `-- name: GetEnrollmentCodeIDByPublicID :one
select id from enrollment_codes where public_id = $1 and fleet_id = $2
`

type GetEnrollmentCodeIDByPublicIDParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	FleetID  int64       `json:"fleet_id"`
}

func (q *Queries) GetEnrollmentCodeIDByPublicID(ctx context.Context, arg GetEnrollmentCodeIDByPublicIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getEnrollmentCodeIDByPublicID, arg.PublicID, arg.FleetID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getFleetByID = `-- name: GetFleetByID :one
select id, public_id, name, kind, created_at from fleets where id = $1
`

func (q *Queries) GetFleetByID(ctx context.Context, id int64) (Fleet, error) {
	row := q.db.QueryRow(ctx, getFleetByID, id)
	var i Fleet
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const getFleetByPublicID = `-- name: GetFleetByPublicID :one
select id, public_id, name, kind, created_at from fleets where public_id = $1
`

func (q *Queries) GetFleetByPublicID(ctx context.Context, publicID pgtype.UUID) (Fleet, error) {
	row := q.db.QueryRow(ctx, getFleetByPublicID, publicID)
	var i Fleet
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const getFleetKind = `-- name: GetFleetKind :one
select kind from fleets where id = $1
`

func (q *Queries) GetFleetKind(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getFleetKind, id)
	var kind string
	err := row.Scan(&kind)
	return kind, err
}

const getInvitation = `-- name: GetInvitation :one
select id, public_id, fleet_id, inviter_id, invitee_email, role, status, created_at, expires_at from invitations where id = $1
`

func (q *Queries) GetInvitation(ctx context.Context, id int64) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.InviterID,
		&i.InviteeEmail,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getInvitationByPublicID = `-- name: GetInvitationByPublicID :one
select id, public_id, fleet_id, inviter_id, invitee_email, role, status, created_at, expires_at from invitations where public_id = $1
`

func (q *Queries) GetInvitationByPublicID(ctx context.Context, publicID pgtype.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByPublicID, publicID)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.InviterID,
		&i.InviteeEmail,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getLabelIDByPublicID = `-- name: GetLabelIDByPublicID :one
select id from labels where public_id = $1 and fleet_id = $2
`

type GetLabelIDByPublicIDParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	FleetID  int64       `json:"fleet_id"`
}

func (q *Queries) GetLabelIDByPublicID(ctx context.Context, arg GetLabelIDByPublicIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getLabelIDByPublicID, arg.PublicID, arg.FleetID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMemberRole = `-- name: GetMemberRole :one
select role from memberships where user_id = $1 and fleet_id = $2
`

type GetMemberRoleParams struct {
	UserID  int64 `json:"user_id"`
	FleetID int64 `json:"fleet_id"`
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.UserID, arg.FleetID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getMemberUserIDByPublicID = `-- name: GetMemberUserIDByPublicID :one
select u.id from users u
join memberships m on m.user_id = u.id
where u.public_id = $1 and m.fleet_id = $2
`

type GetMemberUserIDByPublicIDParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	FleetID  int64       `json:"fleet_id"`
}

func (q *Queries) GetMemberUserIDByPublicID(ctx context.Context, arg GetMemberUserIDByPublicIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getMemberUserIDByPublicID, arg.PublicID, arg.FleetID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMission = `-- name: GetMission :one
select id, public_id, fleet_id, name, key, next_seq, created_at from missions where id = $1
`

func (q *Queries) GetMission(ctx context.Context, id int64) (Mission, error) {
	row := q.db.QueryRow(ctx, getMission, id)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.Name,
		&i.Key,
		&i.NextSeq,
		&i.CreatedAt,
	)
	return i, err
}

const getMissionIDByPublicID = `-- name: GetMissionIDByPublicID :one
select id from missions where public_id = $1 and fleet_id = $2
`

type GetMissionIDByPublicIDParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	FleetID  int64       `json:"fleet_id"`
}

func (q *Queries) GetMissionIDByPublicID(ctx context.Context, arg GetMissionIDByPublicIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getMissionIDByPublicID, arg.PublicID, arg.FleetID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOperation = `-- name: GetOperation :one
select id, public_id, fleet_id, mission_id, seq, parent_id, title, body, status, priority, assignee_type, assignee_id, required_tags, excluded_tags, start_date, due_date, pilot_session_id, pilot_session_kind, session_rover_id, created_by, archived, created_at, updated_at from operations where id = $1 and fleet_id = $2
`

type GetOperationParams struct {
	ID      int64 `json:"id"`
	FleetID int64 `json:"fleet_id"`
}

func (q *Queries) GetOperation(ctx context.Context, arg GetOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperation, arg.ID, arg.FleetID)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.MissionID,
		&i.Seq,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Priority,
		&i.AssigneeType,
		&i.AssigneeID,
		&i.RequiredTags,
		&i.ExcludedTags,
		&i.StartDate,
		&i.DueDate,
		&i.PilotSessionID,
		&i.PilotSessionKind,
		&i.SessionRoverID,
		&i.CreatedBy,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperationIDByPublicID = `-- name: GetOperationIDByPublicID :one

select id from operations where public_id = $1 and fleet_id = $2
`

type GetOperationIDByPublicIDParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	FleetID  int64       `json:"fleet_id"`
}

// ================ public-id resolvers (public id -> internal id) ================
// Each resolves a public id (from a URL path or request body) to the internal
// bigint, scoped to the fleet so cross-tenant ids can't be addressed.
func (q *Queries) GetOperationIDByPublicID(ctx context.Context, arg GetOperationIDByPublicIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getOperationIDByPublicID, arg.PublicID, arg.FleetID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPilot = `-- name: GetPilot :one
select id, public_id, fleet_id, name, kind, created_at from pilots where id = $1 and fleet_id = $2
`

type GetPilotParams struct {
	ID      int64 `json:"id"`
	FleetID int64 `json:"fleet_id"`
}

func (q *Queries) GetPilot(ctx context.Context, arg GetPilotParams) (Pilot, error) {
	row := q.db.QueryRow(ctx, getPilot, arg.ID, arg.FleetID)
	var i Pilot
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const getPilotIDByPublicID = `-- name: GetPilotIDByPublicID :one
select id from pilots where public_id = $1 and fleet_id = $2
`

type GetPilotIDByPublicIDParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	FleetID  int64       `json:"fleet_id"`
}

func (q *Queries) GetPilotIDByPublicID(ctx context.Context, arg GetPilotIDByPublicIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getPilotIDByPublicID, arg.PublicID, arg.FleetID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getRoverByToken = `-- name: GetRoverByToken :one
select id, public_id, fleet_id, name, token, enrollment_code_id, tags, auto_tags, last_seen_at, created_at from rovers where token = $1
`

func (q *Queries) GetRoverByToken(ctx context.Context, token string) (Rover, error) {
	row := q.db.QueryRow(ctx, getRoverByToken, token)
	var i Rover
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.Name,
		&i.Token,
		&i.EnrollmentCodeID,
		&i.Tags,
		&i.AutoTags,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRoverIDByPublicID = `-- name: GetRoverIDByPublicID :one
select id from rovers where public_id = $1 and fleet_id = $2
`

type GetRoverIDByPublicIDParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	FleetID  int64       `json:"fleet_id"`
}

func (q *Queries) GetRoverIDByPublicID(ctx context.Context, arg GetRoverIDByPublicIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRoverIDByPublicID, arg.PublicID, arg.FleetID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getRun = `-- name: GetRun :one
select id, public_id, fleet_id, operation_id, mission_id, rover_id, pilot_id, required_rover_id, pilot, command, state, session_id, needs_input, requested_status, heartbeat_at, created_at, updated_at from runs where id = $1 and fleet_id = $2
`

type GetRunParams struct {
	ID      int64 `json:"id"`
	FleetID int64 `json:"fleet_id"`
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, arg.ID, arg.FleetID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.OperationID,
		&i.MissionID,
		&i.RoverID,
		&i.PilotID,
		&i.RequiredRoverID,
		&i.Pilot,
		&i.Command,
		&i.State,
		&i.SessionID,
		&i.NeedsInput,
		&i.RequestedStatus,
		&i.HeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunIDByPublicID = `-- name: GetRunIDByPublicID :one
select id from runs where public_id = $1 and fleet_id = $2
`

type GetRunIDByPublicIDParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	FleetID  int64       `json:"fleet_id"`
}

func (q *Queries) GetRunIDByPublicID(ctx context.Context, arg GetRunIDByPublicIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRunIDByPublicID, arg.PublicID, arg.FleetID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getRunIDForRover = `-- name: GetRunIDForRover :one
select id from runs where public_id = $1 and fleet_id = $2 and rover_id = $3
`

type GetRunIDForRoverParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	FleetID  int64       `json:"fleet_id"`
	RoverID  pgtype.Int8 `json:"rover_id"`
}

// Resolve a run owned by the calling rover (claimed by it), so one rover can't
// mutate another rover's run.
func (q *Queries) GetRunIDForRover(ctx context.Context, arg GetRunIDForRoverParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRunIDForRover, arg.PublicID, arg.FleetID, arg.RoverID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSessionUser = `-- name: GetSessionUser :one
select u.id, u.public_id, u.email, u.password_hash, u.name, u.created_at from sessions s
join users u on u.id = s.user_id
where s.token = $1 and s.expires_at > now()
`

// Resolve a session cookie to its user (only if unexpired).
func (q *Queries) GetSessionUser(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRow(ctx, getSessionUser, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getSignalIDByPublicID = `-- name: GetSignalIDByPublicID :one
select id from signals where public_id = $1 and fleet_id = $2
`

type GetSignalIDByPublicIDParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	FleetID  int64       `json:"fleet_id"`
}

func (q *Queries) GetSignalIDByPublicID(ctx context.Context, arg GetSignalIDByPublicIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getSignalIDByPublicID, arg.PublicID, arg.FleetID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, public_id, email, password_hash, name, created_at from users where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, public_id, email, password_hash, name, created_at from users where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUserIDByPublicID = `-- name: GetUserIDByPublicID :one
select id from users where public_id = $1
`

func (q *Queries) GetUserIDByPublicID(ctx context.Context, publicID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUserIDByPublicID, publicID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const heartbeat = `-- name: Heartbeat :exec
update runs set heartbeat_at = now()
where id = $1 and fleet_id = $2 and state in ('claimed', 'starting', 'running')
`

type HeartbeatParams struct {
	ID      int64 `json:"id"`
	FleetID int64 `json:"fleet_id"`
}

func (q *Queries) Heartbeat(ctx context.Context, arg HeartbeatParams) error {
	_, err := q.db.Exec(ctx, heartbeat, arg.ID, arg.FleetID)
	return err
}

const invitationsForEmail = `-- name: InvitationsForEmail :many
select i.id, i.public_id, i.fleet_id, i.inviter_id, i.invitee_email, i.role, i.status, i.created_at, i.expires_at, f.name as fleet_name, f.public_id as fleet_public_id
from invitations i join fleets f on f.id = i.fleet_id
where i.invitee_email = $1 and i.status = 'pending' and i.expires_at > now()
order by i.id desc
`

type InvitationsForEmailRow struct {
	ID            int64              `json:"id"`
	PublicID      pgtype.UUID        `json:"public_id"`
	FleetID       int64              `json:"fleet_id"`
	InviterID     int64              `json:"inviter_id"`
	InviteeEmail  string             `json:"invitee_email"`
	Role          string             `json:"role"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	FleetName     string             `json:"fleet_name"`
	FleetPublicID pgtype.UUID        `json:"fleet_public_id"`
}

// Pending invitations addressed to an email (across fleets), with fleet name.
func (q *Queries) InvitationsForEmail(ctx context.Context, inviteeEmail string) ([]InvitationsForEmailRow, error) {
	rows, err := q.db.Query(ctx, invitationsForEmail, inviteeEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvitationsForEmailRow{}
	for rows.Next() {
		var i InvitationsForEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.FleetID,
			&i.InviterID,
			&i.InviteeEmail,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.FleetName,
			&i.FleetPublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isMember = `-- name: IsMember :one
select exists(
    select 1 from memberships where user_id = $1 and fleet_id = $2
)
`

type IsMemberParams struct {
	UserID  int64 `json:"user_id"`
	FleetID int64 `json:"fleet_id"`
}

func (q *Queries) IsMember(ctx context.Context, arg IsMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMember, arg.UserID, arg.FleetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const labelsForOperations = `-- name: LabelsForOperations :many
select ol.operation_id, l.public_id, l.name, l.color
from operation_labels ol join labels l on l.id = ol.label_id
where ol.operation_id = any($1::bigint[])
order by l.name
`

type LabelsForOperationsRow struct {
	OperationID int64       `json:"operation_id"`
	PublicID    pgtype.UUID `json:"public_id"`
	Name        string      `json:"name"`
	Color       string      `json:"color"`
}

// Labels for a set of operations.
func (q *Queries) LabelsForOperations(ctx context.Context, dollar_1 []int64) ([]LabelsForOperationsRow, error) {
	rows, err := q.db.Query(ctx, labelsForOperations, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LabelsForOperationsRow{}
	for rows.Next() {
		var i LabelsForOperationsRow
		if err := rows.Scan(
			&i.OperationID,
			&i.PublicID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildOperations = `-- name: ListChildOperations :many
select id, public_id, fleet_id, mission_id, seq, parent_id, title, body, status, priority, assignee_type, assignee_id, required_tags, excluded_tags, start_date, due_date, pilot_session_id, pilot_session_kind, session_rover_id, created_by, archived, created_at, updated_at from operations where parent_id = $1 order by id
`

func (q *Queries) ListChildOperations(ctx context.Context, parentID pgtype.Int8) ([]Operation, error) {
	rows, err := q.db.Query(ctx, listChildOperations, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.FleetID,
			&i.MissionID,
			&i.Seq,
			&i.ParentID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Priority,
			&i.AssigneeType,
			&i.AssigneeID,
			&i.RequiredTags,
			&i.ExcludedTags,
			&i.StartDate,
			&i.DueDate,
			&i.PilotSessionID,
			&i.PilotSessionKind,
			&i.SessionRoverID,
			&i.CreatedBy,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
select id, public_id, operation_id, author_type, author_id, body, created_at from comments where operation_id = $1 order by id
`

func (q *Queries) ListComments(ctx context.Context, operationID int64) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listComments, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OperationID,
			&i.AuthorType,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrewMembers = `-- name: ListCrewMembers :many
select crew_id, member_type, member_id, role from crew_members where crew_id = $1
`

func (q *Queries) ListCrewMembers(ctx context.Context, crewID int64) ([]CrewMember, error) {
	rows, err := q.db.Query(ctx, listCrewMembers, crewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CrewMember{}
	for rows.Next() {
		var i CrewMember
		if err := rows.Scan(
			&i.CrewID,
			&i.MemberType,
			&i.MemberID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrews = `-- name: ListCrews :many
select id, public_id, fleet_id, name, created_at from crews where fleet_id = $1 order by id
`

func (q *Queries) ListCrews(ctx context.Context, fleetID int64) ([]Crew, error) {
	rows, err := q.db.Query(ctx, listCrews, fleetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Crew{}
	for rows.Next() {
		var i Crew
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.FleetID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrollmentCodes = `-- name: ListEnrollmentCodes :many
select id, public_id, fleet_id, code, label, reusable, expires_at, created_at from enrollment_codes where fleet_id = $1 order by id desc
`

func (q *Queries) ListEnrollmentCodes(ctx context.Context, fleetID int64) ([]EnrollmentCode, error) {
	rows, err := q.db.Query(ctx, listEnrollmentCodes, fleetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnrollmentCode{}
	for rows.Next() {
		var i EnrollmentCode
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.FleetID,
			&i.Code,
			&i.Label,
			&i.Reusable,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetMemberIDs = `-- name: ListFleetMemberIDs :many
select user_id from memberships where fleet_id = $1
`

func (q *Queries) ListFleetMemberIDs(ctx context.Context, fleetID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listFleetMemberIDs, fleetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetsForUser = `-- name: ListFleetsForUser :many
select w.id, w.public_id, w.name, w.kind, w.created_at from fleets w
join memberships m on m.fleet_id = w.id
where m.user_id = $1
order by w.id
`

func (q *Queries) ListFleetsForUser(ctx context.Context, userID int64) ([]Fleet, error) {
	rows, err := q.db.Query(ctx, listFleetsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fleet{}
	for rows.Next() {
		var i Fleet
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitations = `-- name: ListInvitations :many
select id, public_id, fleet_id, inviter_id, invitee_email, role, status, created_at, expires_at from invitations where fleet_id = $1 and status = 'pending' order by id desc
`

func (q *Queries) ListInvitations(ctx context.Context, fleetID int64) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitations, fleetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.FleetID,
			&i.InviterID,
			&i.InviteeEmail,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabels = `-- name: ListLabels :many
select id, public_id, fleet_id, name, color, created_at from labels where fleet_id = $1 order by name
`

func (q *Queries) ListLabels(ctx context.Context, fleetID int64) ([]Label, error) {
	rows, err := q.db.Query(ctx, listLabels, fleetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.FleetID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
select u.public_id as id, u.email, u.name, m.role
from memberships m join users u on u.id = m.user_id
where m.fleet_id = $1
order by m.created_at
`

type ListMembersRow struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
	Name  string      `json:"name"`
	Role  string      `json:"role"`
}

func (q *Queries) ListMembers(ctx context.Context, fleetID int64) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, fleetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissions = `-- name: ListMissions :many
select id, public_id, fleet_id, name, key, next_seq, created_at from missions where fleet_id = $1 order by id
`

func (q *Queries) ListMissions(ctx context.Context, fleetID int64) ([]Mission, error) {
	rows, err := q.db.Query(ctx, listMissions, fleetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mission{}
	for rows.Next() {
		var i Mission
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.FleetID,
			&i.Name,
			&i.Key,
			&i.NextSeq,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperations = `-- name: ListOperations :many
select id, public_id, fleet_id, mission_id, seq, parent_id, title, body, status, priority, assignee_type, assignee_id, required_tags, excluded_tags, start_date, due_date, pilot_session_id, pilot_session_kind, session_rover_id, created_by, archived, created_at, updated_at from operations where fleet_id = $1 order by id desc
`

func (q *Queries) ListOperations(ctx context.Context, fleetID int64) ([]Operation, error) {
	rows, err := q.db.Query(ctx, listOperations, fleetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.FleetID,
			&i.MissionID,
			&i.Seq,
			&i.ParentID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Priority,
			&i.AssigneeType,
			&i.AssigneeID,
			&i.RequiredTags,
			&i.ExcludedTags,
			&i.StartDate,
			&i.DueDate,
			&i.PilotSessionID,
			&i.PilotSessionKind,
			&i.SessionRoverID,
			&i.CreatedBy,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationsByStatus = `-- name: ListOperationsByStatus :many
select id, public_id, fleet_id, mission_id, seq, parent_id, title, body, status, priority, assignee_type, assignee_id, required_tags, excluded_tags, start_date, due_date, pilot_session_id, pilot_session_kind, session_rover_id, created_by, archived, created_at, updated_at from operations
where fleet_id = $1 and status = $2
  and ($3::bigint = 0 or mission_id = $3)
  and ($4::bigint = 0 or id < $4)
  and ($6::smallint = -1 or priority = $6)
  and ($7::text = '' or assignee_type = $7)
  and ($8::bigint = 0 or assignee_id = $8)
  and ($9::bigint = 0 or created_by = $9)
  and ($10::bigint = 0 or exists(select 1 from operation_labels ol where ol.operation_id = operations.id and ol.label_id = $10))
  and ($11::bool or archived = false)
order by id desc
limit $5
`

type ListOperationsByStatusParams struct {
	FleetID  int64  `json:"fleet_id"`
	Status   string `json:"status"`
	Column3  int64  `json:"column_3"`
	Column4  int64  `json:"column_4"`
	Limit    int32  `json:"limit"`
	Column6  int16  `json:"column_6"`
	Column7  string `json:"column_7"`
	Column8  int64  `json:"column_8"`
	Column9  int64  `json:"column_9"`
	Column10 int64  `json:"column_10"`
	Column11 bool   `json:"column_11"`
}

// Board: one status column, keyset-paginated. mission = 0 → all missions;
// before = 0 → first page (newest). Index: operations_board_idx.
// Board column, keyset-paginated, with optional filters (0/” = unset). $6 priority
// (-1=any), $7 assignee_kind (”|user|pilot|crew), $8 assignee_id, $9 creator, $10 label.
func (q *Queries) ListOperationsByStatus(ctx context.Context, arg ListOperationsByStatusParams) ([]Operation, error) {
	rows, err := q.db.Query(ctx, listOperationsByStatus,
		arg.FleetID,
		arg.Status,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.FleetID,
			&i.MissionID,
			&i.Seq,
			&i.ParentID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Priority,
			&i.AssigneeType,
			&i.AssigneeID,
			&i.RequiredTags,
			&i.ExcludedTags,
			&i.StartDate,
			&i.DueDate,
			&i.PilotSessionID,
			&i.PilotSessionKind,
			&i.SessionRoverID,
			&i.CreatedBy,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPRsForOperation = `-- name: ListPRsForOperation :many
select id, public_id, operation_id, url, title, state, number, created_at from pull_requests where operation_id = $1 order by id
`

func (q *Queries) ListPRsForOperation(ctx context.Context, operationID int64) ([]PullRequest, error) {
	rows, err := q.db.Query(ctx, listPRsForOperation, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequest{}
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OperationID,
			&i.Url,
			&i.Title,
			&i.State,
			&i.Number,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPilots = `-- name: ListPilots :many
select id, public_id, fleet_id, name, kind, created_at from pilots where fleet_id = $1 order by id
`

func (q *Queries) ListPilots(ctx context.Context, fleetID int64) ([]Pilot, error) {
	rows, err := q.db.Query(ctx, listPilots, fleetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pilot{}
	for rows.Next() {
		var i Pilot
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.FleetID,
			&i.Name,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsForOperation = `-- name: ListRelationsForOperation :many
select r.public_id as rel_id, r.kind, (r.source_id = $1) as outgoing,
       o.public_id as op_id, o.title, o.status, o.seq, m.public_id as mission_id
from operation_relations r
join operations o on o.id = case when r.source_id = $1 then r.target_id else r.source_id end
join missions m on m.id = o.mission_id
where r.source_id = $1 or r.target_id = $1
order by r.id
`

type ListRelationsForOperationRow struct {
	RelID     pgtype.UUID `json:"rel_id"`
	Kind      string      `json:"kind"`
	Outgoing  bool        `json:"outgoing"`
	OpID      pgtype.UUID `json:"op_id"`
	Title     string      `json:"title"`
	Status    string      `json:"status"`
	Seq       int32       `json:"seq"`
	MissionID pgtype.UUID `json:"mission_id"`
}

// Both directions for one operation, joined to the *other* operation. `outgoing`
// = the queried op is the source (so the row's kind applies as-is; otherwise inverse).
func (q *Queries) ListRelationsForOperation(ctx context.Context, sourceID int64) ([]ListRelationsForOperationRow, error) {
	rows, err := q.db.Query(ctx, listRelationsForOperation, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelationsForOperationRow{}
	for rows.Next() {
		var i ListRelationsForOperationRow
		if err := rows.Scan(
			&i.RelID,
			&i.Kind,
			&i.Outgoing,
			&i.OpID,
			&i.Title,
			&i.Status,
			&i.Seq,
			&i.MissionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoversWithStatus = `-- name: ListRoversWithStatus :many
select r.id, r.public_id, r.fleet_id, r.name, r.token, r.enrollment_code_id, r.tags, r.auto_tags, r.last_seen_at, r.created_at,
       exists(
           select 1 from runs x
           where x.rover_id = r.id and x.state in ('claimed', 'starting', 'running')
       ) as busy
from rovers r
where r.fleet_id = $1
order by r.id
`

type ListRoversWithStatusRow struct {
	ID               int64              `json:"id"`
	PublicID         pgtype.UUID        `json:"public_id"`
	FleetID          int64              `json:"fleet_id"`
	Name             string             `json:"name"`
	Token            string             `json:"token"`
	EnrollmentCodeID pgtype.Int8        `json:"enrollment_code_id"`
	Tags             []string           `json:"tags"`
	AutoTags         []string           `json:"auto_tags"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Busy             bool               `json:"busy"`
}

// List rovers with a computed "busy" flag (has an active run).
func (q *Queries) ListRoversWithStatus(ctx context.Context, fleetID int64) ([]ListRoversWithStatusRow, error) {
	rows, err := q.db.Query(ctx, listRoversWithStatus, fleetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoversWithStatusRow{}
	for rows.Next() {
		var i ListRoversWithStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.FleetID,
			&i.Name,
			&i.Token,
			&i.EnrollmentCodeID,
			&i.Tags,
			&i.AutoTags,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.Busy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunArtifacts = `-- name: ListRunArtifacts :many
select id, run_id, kind, name, content, created_at from artifacts where run_id = $1 order by id
`

func (q *Queries) ListRunArtifacts(ctx context.Context, runID int64) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listRunArtifacts, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Kind,
			&i.Name,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunEvents = `-- name: ListRunEvents :many
select id, run_id, kind, message, created_at from run_events where run_id = $1 order by id
`

func (q *Queries) ListRunEvents(ctx context.Context, runID int64) ([]RunEvent, error) {
	rows, err := q.db.Query(ctx, listRunEvents, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunEvent{}
	for rows.Next() {
		var i RunEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Kind,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunMessages = `-- name: ListRunMessages :many
select id, run_id, seq, type, tool, content, input, output, created_at from run_messages where run_id = $1 order by seq, id
`

func (q *Queries) ListRunMessages(ctx context.Context, runID int64) ([]RunMessage, error) {
	rows, err := q.db.Query(ctx, listRunMessages, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunMessage{}
	for rows.Next() {
		var i RunMessage
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Seq,
			&i.Type,
			&i.Tool,
			&i.Content,
			&i.Input,
			&i.Output,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
select id, public_id, fleet_id, operation_id, mission_id, rover_id, pilot_id, required_rover_id, pilot, command, state, session_id, needs_input, requested_status, heartbeat_at, created_at, updated_at from runs where fleet_id = $1 order by id desc
`

func (q *Queries) ListRuns(ctx context.Context, fleetID int64) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRuns, fleetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.FleetID,
			&i.OperationID,
			&i.MissionID,
			&i.RoverID,
			&i.PilotID,
			&i.RequiredRoverID,
			&i.Pilot,
			&i.Command,
			&i.State,
			&i.SessionID,
			&i.NeedsInput,
			&i.RequestedStatus,
			&i.HeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByOperation = `-- name: ListRunsByOperation :many
select id, public_id, fleet_id, operation_id, mission_id, rover_id, pilot_id, required_rover_id, pilot, command, state, session_id, needs_input, requested_status, heartbeat_at, created_at, updated_at from runs where operation_id = $1 order by id desc
`

func (q *Queries) ListRunsByOperation(ctx context.Context, operationID int64) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsByOperation, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.FleetID,
			&i.OperationID,
			&i.MissionID,
			&i.RoverID,
			&i.PilotID,
			&i.RequiredRoverID,
			&i.Pilot,
			&i.Command,
			&i.State,
			&i.SessionID,
			&i.NeedsInput,
			&i.RequestedStatus,
			&i.HeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignals = `-- name: ListSignals :many
select id, public_id, fleet_id, recipient_user_id, operation_id, type, severity, title, body, read, archived, created_at from signals
where fleet_id = $1 and recipient_user_id = $2 and archived = false
order by read, id desc
`

type ListSignalsParams struct {
	FleetID         int64 `json:"fleet_id"`
	RecipientUserID int64 `json:"recipient_user_id"`
}

func (q *Queries) ListSignals(ctx context.Context, arg ListSignalsParams) ([]Signal, error) {
	rows, err := q.db.Query(ctx, listSignals, arg.FleetID, arg.RecipientUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Signal{}
	for rows.Next() {
		var i Signal
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.FleetID,
			&i.RecipientUserID,
			&i.OperationID,
			&i.Type,
			&i.Severity,
			&i.Title,
			&i.Body,
			&i.Read,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFleet = `-- name: LockFleet :exec
select id from fleets where id = $1 for update
`

func (q *Queries) LockFleet(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, lockFleet, id)
	return err
}

const markSignalRead = `-- name: MarkSignalRead :exec
update signals set read = true
where id = $1 and fleet_id = $2 and recipient_user_id = $3
`

type MarkSignalReadParams struct {
	ID              int64 `json:"id"`
	FleetID         int64 `json:"fleet_id"`
	RecipientUserID int64 `json:"recipient_user_id"`
}

func (q *Queries) MarkSignalRead(ctx context.Context, arg MarkSignalReadParams) error {
	_, err := q.db.Exec(ctx, markSignalRead, arg.ID, arg.FleetID, arg.RecipientUserID)
	return err
}

const notifyFleetChanged = `-- name: NotifyFleetChanged :exec
select pg_notify('ufo_changed', json_build_object('t', 'rover', 'fleet', $1::bigint)::text)
`

func (q *Queries) NotifyFleetChanged(ctx context.Context, dollar_1 int64) error {
	_, err := q.db.Exec(ctx, notifyFleetChanged, dollar_1)
	return err
}

const publicIDsForCrews = `-- name: PublicIDsForCrews :many
select id, public_id from crews where id = any($1::bigint[])
`

type PublicIDsForCrewsRow struct {
	ID       int64       `json:"id"`
	PublicID pgtype.UUID `json:"public_id"`
}

func (q *Queries) PublicIDsForCrews(ctx context.Context, dollar_1 []int64) ([]PublicIDsForCrewsRow, error) {
	rows, err := q.db.Query(ctx, publicIDsForCrews, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicIDsForCrewsRow{}
	for rows.Next() {
		var i PublicIDsForCrewsRow
		if err := rows.Scan(&i.ID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicIDsForMissions = `-- name: PublicIDsForMissions :many
select id, public_id from missions where id = any($1::bigint[])
`

type PublicIDsForMissionsRow struct {
	ID       int64       `json:"id"`
	PublicID pgtype.UUID `json:"public_id"`
}

func (q *Queries) PublicIDsForMissions(ctx context.Context, dollar_1 []int64) ([]PublicIDsForMissionsRow, error) {
	rows, err := q.db.Query(ctx, publicIDsForMissions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicIDsForMissionsRow{}
	for rows.Next() {
		var i PublicIDsForMissionsRow
		if err := rows.Scan(&i.ID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicIDsForOperations = `-- name: PublicIDsForOperations :many
select id, public_id from operations where id = any($1::bigint[])
`

type PublicIDsForOperationsRow struct {
	ID       int64       `json:"id"`
	PublicID pgtype.UUID `json:"public_id"`
}

func (q *Queries) PublicIDsForOperations(ctx context.Context, dollar_1 []int64) ([]PublicIDsForOperationsRow, error) {
	rows, err := q.db.Query(ctx, publicIDsForOperations, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicIDsForOperationsRow{}
	for rows.Next() {
		var i PublicIDsForOperationsRow
		if err := rows.Scan(&i.ID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicIDsForPilots = `-- name: PublicIDsForPilots :many
select id, public_id from pilots where id = any($1::bigint[])
`

type PublicIDsForPilotsRow struct {
	ID       int64       `json:"id"`
	PublicID pgtype.UUID `json:"public_id"`
}

func (q *Queries) PublicIDsForPilots(ctx context.Context, dollar_1 []int64) ([]PublicIDsForPilotsRow, error) {
	rows, err := q.db.Query(ctx, publicIDsForPilots, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicIDsForPilotsRow{}
	for rows.Next() {
		var i PublicIDsForPilotsRow
		if err := rows.Scan(&i.ID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicIDsForUsers = `-- name: PublicIDsForUsers :many

select id, public_id from users where id = any($1::bigint[])
`

type PublicIDsForUsersRow struct {
	ID       int64       `json:"id"`
	PublicID pgtype.UUID `json:"public_id"`
}

// ============ batch id -> public_id maps (DTO reference expansion) ==========
// Batch-resolve internal ids for DTO reference expansion.
func (q *Queries) PublicIDsForUsers(ctx context.Context, dollar_1 []int64) ([]PublicIDsForUsersRow, error) {
	rows, err := q.db.Query(ctx, publicIDsForUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicIDsForUsersRow{}
	for rows.Next() {
		var i PublicIDsForUsersRow
		if err := rows.Scan(&i.ID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactionExists = `-- name: ReactionExists :one

select exists(select 1 from reactions where target_type = $1 and target_id = $2 and user_id = $3 and emoji = $4)
`

type ReactionExistsParams struct {
	TargetType string `json:"target_type"`
	TargetID   int64  `json:"target_id"`
	UserID     int64  `json:"user_id"`
	Emoji      string `json:"emoji"`
}

// One generic reaction API over (target_type, target_id) — serves operations + comments.
func (q *Queries) ReactionExists(ctx context.Context, arg ReactionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, reactionExists,
		arg.TargetType,
		arg.TargetID,
		arg.UserID,
		arg.Emoji,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const reactionsForTargets = `-- name: ReactionsForTargets :many
select r.target_id, r.emoji, count(*)::bigint as n, bool_or(r.user_id = $3) as mine,
       array_agg(coalesce(nullif(u.name, ''), u.email) order by r.created_at)::text[] as users
from reactions r join users u on u.id = r.user_id
where r.target_type = $1 and r.target_id = any($2::bigint[])
group by r.target_id, r.emoji
order by min(r.created_at)
`

type ReactionsForTargetsParams struct {
	TargetType string  `json:"target_type"`
	Column2    []int64 `json:"column_2"`
	UserID     int64   `json:"user_id"`
}

type ReactionsForTargetsRow struct {
	TargetID int64    `json:"target_id"`
	Emoji    string   `json:"emoji"`
	N        int64    `json:"n"`
	Mine     bool     `json:"mine"`
	Users    []string `json:"users"`
}

// Reactions for a set of targets of one type: count, whether the caller ($3) reacted, and
// reactors (oldest first, for the hover tooltip). Emoji groups ordered by first use.
func (q *Queries) ReactionsForTargets(ctx context.Context, arg ReactionsForTargetsParams) ([]ReactionsForTargetsRow, error) {
	rows, err := q.db.Query(ctx, reactionsForTargets, arg.TargetType, arg.Column2, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReactionsForTargetsRow{}
	for rows.Next() {
		var i ReactionsForTargetsRow
		if err := rows.Scan(
			&i.TargetID,
			&i.Emoji,
			&i.N,
			&i.Mine,
			&i.Users,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCrewMember = `-- name: RemoveCrewMember :exec
delete from crew_members where crew_id = $1 and member_type = $2 and member_id = $3
`

type RemoveCrewMemberParams struct {
	CrewID     int64  `json:"crew_id"`
	MemberType string `json:"member_type"`
	MemberID   int64  `json:"member_id"`
}

func (q *Queries) RemoveCrewMember(ctx context.Context, arg RemoveCrewMemberParams) error {
	_, err := q.db.Exec(ctx, removeCrewMember, arg.CrewID, arg.MemberType, arg.MemberID)
	return err
}

const removeMember = `-- name: RemoveMember :exec
delete from memberships where user_id = $1 and fleet_id = $2
`

type RemoveMemberParams struct {
	UserID  int64 `json:"user_id"`
	FleetID int64 `json:"fleet_id"`
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.UserID, arg.FleetID)
	return err
}

const removeOperationLabel = `-- name: RemoveOperationLabel :exec
delete from operation_labels where operation_id = $1 and label_id = $2
`

type RemoveOperationLabelParams struct {
	OperationID int64 `json:"operation_id"`
	LabelID     int64 `json:"label_id"`
}

func (q *Queries) RemoveOperationLabel(ctx context.Context, arg RemoveOperationLabelParams) error {
	_, err := q.db.Exec(ctx, removeOperationLabel, arg.OperationID, arg.LabelID)
	return err
}

const removeReaction = `-- name: RemoveReaction :exec
delete from reactions where target_type = $1 and target_id = $2 and user_id = $3 and emoji = $4
`

type RemoveReactionParams struct {
	TargetType string `json:"target_type"`
	TargetID   int64  `json:"target_id"`
	UserID     int64  `json:"user_id"`
	Emoji      string `json:"emoji"`
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) error {
	_, err := q.db.Exec(ctx, removeReaction,
		arg.TargetType,
		arg.TargetID,
		arg.UserID,
		arg.Emoji,
	)
	return err
}

const requeueExpiredRuns = `-- name: RequeueExpiredRuns :many
update runs
set state = 'queued', heartbeat_at = null, rover_id = null, updated_at = now()
where state in ('claimed', 'starting', 'running')
  and heartbeat_at is not null
  and heartbeat_at < now() - make_interval(secs => $1::float8)
returning id
`

// Requeue runs whose rover went silent (heartbeat older than the lease).
func (q *Queries) RequeueExpiredRuns(ctx context.Context, dollar_1 float64) ([]int64, error) {
	rows, err := q.db.Query(ctx, requeueExpiredRuns, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveFleetForMember = `-- name: ResolveFleetForMember :one
select f.id from fleets f
join memberships m on m.fleet_id = f.id
where f.public_id = $1 and m.user_id = $2
`

type ResolveFleetForMemberParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	UserID   int64       `json:"user_id"`
}

// Resolve a fleet's public id to its internal id, asserting membership.
func (q *Queries) ResolveFleetForMember(ctx context.Context, arg ResolveFleetForMemberParams) (int64, error) {
	row := q.db.QueryRow(ctx, resolveFleetForMember, arg.PublicID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const roverLastSeen = `-- name: RoverLastSeen :one
select last_seen_at from rovers where id = $1
`

func (q *Queries) RoverLastSeen(ctx context.Context, id int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, roverLastSeen, id)
	var last_seen_at pgtype.Timestamptz
	err := row.Scan(&last_seen_at)
	return last_seen_at, err
}

const searchOperations = `-- name: SearchOperations :many
select o.id, o.public_id, o.fleet_id, o.mission_id, o.seq, o.parent_id, o.title, o.body, o.status, o.priority, o.assignee_type, o.assignee_id, o.required_tags, o.excluded_tags, o.start_date, o.due_date, o.pilot_session_id, o.pilot_session_kind, o.session_rover_id, o.created_by, o.archived, o.created_at, o.updated_at, m.public_id as mission_public_id, m.key as mission_key
from operations o join missions m on m.id = o.mission_id
where o.fleet_id = $1
  and (o.title ilike '%' || $2 || '%' or cast(o.seq as text) = $2)
order by o.id desc
limit 20
`

type SearchOperationsParams struct {
	FleetID int64       `json:"fleet_id"`
	Column2 pgtype.Text `json:"column_2"`
}

type SearchOperationsRow struct {
	ID               int64              `json:"id"`
	PublicID         pgtype.UUID        `json:"public_id"`
	FleetID          int64              `json:"fleet_id"`
	MissionID        int64              `json:"mission_id"`
	Seq              int32              `json:"seq"`
	ParentID         pgtype.Int8        `json:"parent_id"`
	Title            string             `json:"title"`
	Body             string             `json:"body"`
	Status           string             `json:"status"`
	Priority         int16              `json:"priority"`
	AssigneeType     pgtype.Text        `json:"assignee_type"`
	AssigneeID       pgtype.Int8        `json:"assignee_id"`
	RequiredTags     []string           `json:"required_tags"`
	ExcludedTags     []string           `json:"excluded_tags"`
	StartDate        pgtype.Date        `json:"start_date"`
	DueDate          pgtype.Date        `json:"due_date"`
	PilotSessionID   pgtype.Text        `json:"pilot_session_id"`
	PilotSessionKind pgtype.Text        `json:"pilot_session_kind"`
	SessionRoverID   pgtype.Int8        `json:"session_rover_id"`
	CreatedBy        pgtype.Int8        `json:"created_by"`
	Archived         bool               `json:"archived"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	MissionPublicID  pgtype.UUID        `json:"mission_public_id"`
	MissionKey       string             `json:"mission_key"`
}

// Typeahead for linking operations: match title or numeric seq, newest first.
func (q *Queries) SearchOperations(ctx context.Context, arg SearchOperationsParams) ([]SearchOperationsRow, error) {
	rows, err := q.db.Query(ctx, searchOperations, arg.FleetID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchOperationsRow{}
	for rows.Next() {
		var i SearchOperationsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.FleetID,
			&i.MissionID,
			&i.Seq,
			&i.ParentID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Priority,
			&i.AssigneeType,
			&i.AssigneeID,
			&i.RequiredTags,
			&i.ExcludedTags,
			&i.StartDate,
			&i.DueDate,
			&i.PilotSessionID,
			&i.PilotSessionKind,
			&i.SessionRoverID,
			&i.CreatedBy,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MissionPublicID,
			&i.MissionKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInvitationStatus = `-- name: SetInvitationStatus :exec
update invitations set status = $2 where id = $1
`

type SetInvitationStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetInvitationStatus(ctx context.Context, arg SetInvitationStatusParams) error {
	_, err := q.db.Exec(ctx, setInvitationStatus, arg.ID, arg.Status)
	return err
}

const setOperationArchived = `-- name: SetOperationArchived :exec
update operations set archived = $3, updated_at = now() where id = $1 and fleet_id = $2
`

type SetOperationArchivedParams struct {
	ID       int64 `json:"id"`
	FleetID  int64 `json:"fleet_id"`
	Archived bool  `json:"archived"`
}

func (q *Queries) SetOperationArchived(ctx context.Context, arg SetOperationArchivedParams) error {
	_, err := q.db.Exec(ctx, setOperationArchived, arg.ID, arg.FleetID, arg.Archived)
	return err
}

const setOperationDates = `-- name: SetOperationDates :exec
update operations set start_date = $3, due_date = $4, updated_at = now() where id = $1 and fleet_id = $2
`

type SetOperationDatesParams struct {
	ID        int64       `json:"id"`
	FleetID   int64       `json:"fleet_id"`
	StartDate pgtype.Date `json:"start_date"`
	DueDate   pgtype.Date `json:"due_date"`
}

func (q *Queries) SetOperationDates(ctx context.Context, arg SetOperationDatesParams) error {
	_, err := q.db.Exec(ctx, setOperationDates,
		arg.ID,
		arg.FleetID,
		arg.StartDate,
		arg.DueDate,
	)
	return err
}

const setOperationParent = `-- name: SetOperationParent :exec
update operations set parent_id = $3, updated_at = now() where id = $1 and fleet_id = $2
`

type SetOperationParentParams struct {
	ID       int64       `json:"id"`
	FleetID  int64       `json:"fleet_id"`
	ParentID pgtype.Int8 `json:"parent_id"`
}

func (q *Queries) SetOperationParent(ctx context.Context, arg SetOperationParentParams) error {
	_, err := q.db.Exec(ctx, setOperationParent, arg.ID, arg.FleetID, arg.ParentID)
	return err
}

const setOperationPriority = `-- name: SetOperationPriority :exec
update operations set priority = $3, updated_at = now() where id = $1 and fleet_id = $2
`

type SetOperationPriorityParams struct {
	ID       int64 `json:"id"`
	FleetID  int64 `json:"fleet_id"`
	Priority int16 `json:"priority"`
}

func (q *Queries) SetOperationPriority(ctx context.Context, arg SetOperationPriorityParams) error {
	_, err := q.db.Exec(ctx, setOperationPriority, arg.ID, arg.FleetID, arg.Priority)
	return err
}

const setOperationSession = `-- name: SetOperationSession :exec
update operations set pilot_session_id = $2, pilot_session_kind = $3, session_rover_id = $5 where id = $1 and fleet_id = $4
`

type SetOperationSessionParams struct {
	ID               int64       `json:"id"`
	PilotSessionID   pgtype.Text `json:"pilot_session_id"`
	PilotSessionKind pgtype.Text `json:"pilot_session_kind"`
	FleetID          int64       `json:"fleet_id"`
	SessionRoverID   pgtype.Int8 `json:"session_rover_id"`
}

func (q *Queries) SetOperationSession(ctx context.Context, arg SetOperationSessionParams) error {
	_, err := q.db.Exec(ctx, setOperationSession,
		arg.ID,
		arg.PilotSessionID,
		arg.PilotSessionKind,
		arg.FleetID,
		arg.SessionRoverID,
	)
	return err
}

const setOperationStatus = `-- name: SetOperationStatus :exec
update operations set status = $3, updated_at = now() where id = $1 and fleet_id = $2
`

type SetOperationStatusParams struct {
	ID      int64  `json:"id"`
	FleetID int64  `json:"fleet_id"`
	Status  string `json:"status"`
}

func (q *Queries) SetOperationStatus(ctx context.Context, arg SetOperationStatusParams) error {
	_, err := q.db.Exec(ctx, setOperationStatus, arg.ID, arg.FleetID, arg.Status)
	return err
}

const setRoverAutoTags = `-- name: SetRoverAutoTags :exec
update rovers set auto_tags = $2 where id = $1
`

type SetRoverAutoTagsParams struct {
	ID       int64    `json:"id"`
	AutoTags []string `json:"auto_tags"`
}

func (q *Queries) SetRoverAutoTags(ctx context.Context, arg SetRoverAutoTagsParams) error {
	_, err := q.db.Exec(ctx, setRoverAutoTags, arg.ID, arg.AutoTags)
	return err
}

const setRoverTags = `-- name: SetRoverTags :exec
update rovers set tags = $3 where id = $1 and fleet_id = $2
`

type SetRoverTagsParams struct {
	ID      int64    `json:"id"`
	FleetID int64    `json:"fleet_id"`
	Tags    []string `json:"tags"`
}

func (q *Queries) SetRoverTags(ctx context.Context, arg SetRoverTagsParams) error {
	_, err := q.db.Exec(ctx, setRoverTags, arg.ID, arg.FleetID, arg.Tags)
	return err
}

const setRunNeedsInput = `-- name: SetRunNeedsInput :exec
update runs set needs_input = true where id = $1 and fleet_id = $2
`

type SetRunNeedsInputParams struct {
	ID      int64 `json:"id"`
	FleetID int64 `json:"fleet_id"`
}

func (q *Queries) SetRunNeedsInput(ctx context.Context, arg SetRunNeedsInputParams) error {
	_, err := q.db.Exec(ctx, setRunNeedsInput, arg.ID, arg.FleetID)
	return err
}

const setRunRequestedStatus = `-- name: SetRunRequestedStatus :exec
update runs set requested_status = $3 where id = $1 and fleet_id = $2
`

type SetRunRequestedStatusParams struct {
	ID              int64  `json:"id"`
	FleetID         int64  `json:"fleet_id"`
	RequestedStatus string `json:"requested_status"`
}

func (q *Queries) SetRunRequestedStatus(ctx context.Context, arg SetRunRequestedStatusParams) error {
	_, err := q.db.Exec(ctx, setRunRequestedStatus, arg.ID, arg.FleetID, arg.RequestedStatus)
	return err
}

const setRunSession = `-- name: SetRunSession :exec
update runs set session_id = $2 where id = $1 and fleet_id = $3
`

type SetRunSessionParams struct {
	ID        int64       `json:"id"`
	SessionID pgtype.Text `json:"session_id"`
	FleetID   int64       `json:"fleet_id"`
}

func (q *Queries) SetRunSession(ctx context.Context, arg SetRunSessionParams) error {
	_, err := q.db.Exec(ctx, setRunSession, arg.ID, arg.SessionID, arg.FleetID)
	return err
}

const setRunState = `-- name: SetRunState :one
update runs
set state = $2, updated_at = now()
where id = $1 and fleet_id = $3
returning id, public_id, fleet_id, operation_id, mission_id, rover_id, pilot_id, required_rover_id, pilot, command, state, session_id, needs_input, requested_status, heartbeat_at, created_at, updated_at
`

type SetRunStateParams struct {
	ID      int64  `json:"id"`
	State   string `json:"state"`
	FleetID int64  `json:"fleet_id"`
}

func (q *Queries) SetRunState(ctx context.Context, arg SetRunStateParams) (Run, error) {
	row := q.db.QueryRow(ctx, setRunState, arg.ID, arg.State, arg.FleetID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.OperationID,
		&i.MissionID,
		&i.RoverID,
		&i.PilotID,
		&i.RequiredRoverID,
		&i.Pilot,
		&i.Command,
		&i.State,
		&i.SessionID,
		&i.NeedsInput,
		&i.RequestedStatus,
		&i.HeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const subOpProgress = `-- name: SubOpProgress :many
select parent_id, count(*)::bigint as total, count(*) filter (where status = 'done')::bigint as done
from operations where parent_id = any($1::bigint[]) group by parent_id
`

type SubOpProgressRow struct {
	ParentID pgtype.Int8 `json:"parent_id"`
	Total    int64       `json:"total"`
	Done     int64       `json:"done"`
}

// Sub-operation progress per parent (total + done), batched for the board.
func (q *Queries) SubOpProgress(ctx context.Context, dollar_1 []int64) ([]SubOpProgressRow, error) {
	rows, err := q.db.Query(ctx, subOpProgress, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubOpProgressRow{}
	for rows.Next() {
		var i SubOpProgressRow
		if err := rows.Scan(&i.ParentID, &i.Total, &i.Done); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchOperation = `-- name: TouchOperation :exec
update operations set updated_at = now() where id = $1 and fleet_id = $2
`

type TouchOperationParams struct {
	ID      int64 `json:"id"`
	FleetID int64 `json:"fleet_id"`
}

func (q *Queries) TouchOperation(ctx context.Context, arg TouchOperationParams) error {
	_, err := q.db.Exec(ctx, touchOperation, arg.ID, arg.FleetID)
	return err
}

const touchRover = `-- name: TouchRover :exec
update rovers set last_seen_at = now() where id = $1
`

func (q *Queries) TouchRover(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchRover, id)
	return err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
update memberships set role = $3 where user_id = $1 and fleet_id = $2
`

type UpdateMemberRoleParams struct {
	UserID  int64  `json:"user_id"`
	FleetID int64  `json:"fleet_id"`
	Role    string `json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.UserID, arg.FleetID, arg.Role)
	return err
}

const updateMission = `-- name: UpdateMission :one
update missions set name = $3, key = $4
where id = $1 and fleet_id = $2
returning id, public_id, fleet_id, name, key, next_seq, created_at
`

type UpdateMissionParams struct {
	ID      int64  `json:"id"`
	FleetID int64  `json:"fleet_id"`
	Name    string `json:"name"`
	Key     string `json:"key"`
}

func (q *Queries) UpdateMission(ctx context.Context, arg UpdateMissionParams) (Mission, error) {
	row := q.db.QueryRow(ctx, updateMission,
		arg.ID,
		arg.FleetID,
		arg.Name,
		arg.Key,
	)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FleetID,
		&i.Name,
		&i.Key,
		&i.NextSeq,
		&i.CreatedAt,
	)
	return i, err
}

const updateOperationTags = `-- name: UpdateOperationTags :exec
update operations set required_tags = $3, excluded_tags = $4, updated_at = now() where id = $1 and fleet_id = $2
`

type UpdateOperationTagsParams struct {
	ID           int64    `json:"id"`
	FleetID      int64    `json:"fleet_id"`
	RequiredTags []string `json:"required_tags"`
	ExcludedTags []string `json:"excluded_tags"`
}

func (q *Queries) UpdateOperationTags(ctx context.Context, arg UpdateOperationTagsParams) error {
	_, err := q.db.Exec(ctx, updateOperationTags,
		arg.ID,
		arg.FleetID,
		arg.RequiredTags,
		arg.ExcludedTags,
	)
	return err
}
